Repository suiet/suiet, pull requests merged in 2022-08, with the labels that each got.

#15 feat: add router and link
  package-lock.json
  packages/chrome/src/App.css
  packages/chrome/src/App.tsx
  packages/chrome/src/components/AppLayout/Menu/index.tsx
  packages/chrome/src/main.tsx
Labels: enhancement

#18 feat: add transaction detail and setting page
  packages/chrome/src/App.tsx
  packages/chrome/src/components/AppLayout/Menu/index.tsx
  packages/chrome/src/pages/SettingsPage/assets/check.svg
  packages/chrome/src/pages/SettingsPage/assets/network-type-icon-a.svg
  packages/chrome/src/pages/SettingsPage/assets/network-type-icon.svg
  packages/chrome/src/pages/SettingsPage/assets/not-check.svg
  packages/chrome/src/pages/SettingsPage/index.tsx
  packages/chrome/src/pages/SettingsPage/network.scss
  packages/chrome/src/pages/SettingsPage/network.tsx
  packages/chrome/src/pages/SettingsPage/security.scss
  packages/chrome/src/pages/SettingsPage/security.tsx
  packages/chrome/src/pages/TransactionFlow/TransactionItem.tsx
  packages/chrome/src/pages/TransactionFlow/index.tsx
  packages/chrome/src/pages/TransactionFlow/transactionDetail.scss
  packages/chrome/src/pages/TransactionFlow/transactionDetail.tsx
  packages/chrome/src/pages/TransactionFlow/transactionItem.scss
Labels: enhancement

#20 feat: add qr-code component
  package-lock.json
  packages/chrome/package.json
  packages/chrome/src/pages/MainPage/Dashboard/index.module.scss
  packages/chrome/src/pages/MainPage/Dashboard/index.tsx
Labels: enhancement

#21 chore: add Jest as test framework
  package-lock.json
  packages/core/.gitignore
  packages/core/jest.config.ts
  packages/core/package.json
  packages/core/src/Wallet.ts
  packages/core/src/hello-world.ts
  packages/core/tests/hello-world.test.ts
Labels: chore

#26 chore(ext): add testing reset button
  packages/chrome/src/pages/SettingsPage/index.tsx
  packages/chrome/src/store/app-context.ts
Labels: chore

#29 ci(core): update bundle toolchains
  package-lock.json
  packages/core/package.json
  packages/core/rollup.config.ts
Labels: ci

#31 chore(ext): remove useless codes and ensure build success
  packages/chrome/src/hooks/index.ts
  packages/chrome/src/utils/storage.ts
Labels: chore

#34 feat: add wallet setting
  packages/chrome/src/assets/avatars/avatar_1.svg
  packages/chrome/src/assets/avatars/avatar_2.svg
  packages/chrome/src/assets/avatars/avatar_3.svg
  packages/chrome/src/assets/avatars/avatar_4.svg
  packages/chrome/src/assets/avatars/default.svg
  packages/chrome/src/constants/avatar.ts
  packages/chrome/src/hooks/useWallet.ts
  packages/chrome/src/pages/AppLayout/Header/index.tsx
  packages/chrome/src/pages/SettingsPage/wallet.scss
  packages/chrome/src/pages/SettingsPage/wallet.tsx
  packages/core/src/api/index.ts
Labels: enhancement

#37 feat(ext): enable wallet switch
  packages/chrome/src/components/WalletSwitcher/index.module.scss
  packages/chrome/src/components/WalletSwitcher/index.tsx
  packages/chrome/src/hooks/useAccount.ts
  packages/chrome/src/pages/AppLayout/Header/index.tsx
  packages/chrome/src/pages/MainPage/Dashboard/index.tsx
  packages/chrome/src/pages/SettingsPage/index.tsx
  packages/core/src/api/index.ts
  packages/core/src/storage/Storage.ts
  packages/core/src/storage/indexeddb.ts
Labels: enhancement

#38 feat: change settings
  packages/chrome/src/assets/avatars/avatar_1.svg
  packages/chrome/src/assets/avatars/avatar_2.svg
  packages/chrome/src/assets/avatars/avatar_3.svg
  packages/chrome/src/assets/avatars/avatar_4.svg
  packages/chrome/src/components/Button/index.module.scss
  packages/chrome/src/pages/AppLayout/Header/index.tsx
  packages/chrome/src/pages/AppLayout/index.tsx
  packages/chrome/src/pages/OnBoarding/CreateNewWallet/index.tsx
  packages/chrome/src/pages/OnBoarding/ImportWallet/index.tsx
  packages/chrome/src/pages/SettingsPage/assets/cancel.svg
  packages/chrome/src/pages/SettingsPage/assets/net.svg
  packages/chrome/src/pages/SettingsPage/assets/right-arrow.svg
  packages/chrome/src/pages/SettingsPage/assets/security.svg
  packages/chrome/src/pages/SettingsPage/assets/wallet.svg
  packages/chrome/src/pages/SettingsPage/common.scss
  packages/chrome/src/pages/SettingsPage/index.scss
  packages/chrome/src/pages/SettingsPage/index.tsx
  packages/chrome/src/pages/SettingsPage/network.scss
  packages/chrome/src/pages/SettingsPage/network.tsx
  packages/chrome/src/pages/SettingsPage/security.scss
  packages/chrome/src/pages/SettingsPage/security.tsx
  packages/chrome/src/pages/SettingsPage/wallet.scss
  packages/chrome/src/pages/SettingsPage/wallet.tsx
  packages/chrome/src/store/index.ts
  packages/chrome/src/store/wallet.ts
Labels: enhancement

#39 fix(core): set sui dep as external
  packages/core/package.json
  packages/core/rollup.config.ts
Labels: bug
