Repository suiet/suiet, pull requests merged in 2022-09, with the labels that each got.

#42 feat: add security setting
  packages/chrome/src/components/Modal/index.module.scss
  packages/chrome/src/pages/OnBoarding/SavePhrase/index.tsx
  packages/chrome/src/pages/OnBoarding/SetPassword/index.tsx
  packages/chrome/src/pages/SettingsPage/index.tsx
  packages/chrome/src/pages/SettingsPage/security.module.scss
  packages/chrome/src/pages/SettingsPage/security.scss
  packages/chrome/src/pages/SettingsPage/security.tsx
Labels: enhancement

#43 feat: add empty page
  packages/chrome/src/pages/TransactionFlow/Empty.tsx
  packages/chrome/src/pages/TransactionFlow/assets/airdrop.svg
  packages/chrome/src/pages/TransactionFlow/assets/empty.svg
  packages/chrome/src/pages/TransactionFlow/assets/fail.svg
  packages/chrome/src/pages/TransactionFlow/assets/receive.svg
  packages/chrome/src/pages/TransactionFlow/assets/send.svg
  packages/chrome/src/pages/TransactionFlow/empty.module.scss
  packages/chrome/src/pages/TransactionFlow/index.scss
  packages/chrome/src/pages/TransactionFlow/index.tsx
  packages/chrome/src/pages/TransactionFlow/transactionItem.scss
Labels: enhancement

#44 fix: fix old pass
  package.json
  packages/chrome/src/pages/OnBoarding/SetPassword/index.tsx
  packages/chrome/src/pages/SettingsPage/security.tsx
  packages/chrome/src/pages/TransactionFlow/index.tsx
Labels: bug

#46 feat: wallet balance
  packages/chrome/src/hooks/useCoinBalance.ts
  packages/core/src/provider.ts
Labels: enhancement

#48 feat(ext): return to home after switching wallet
  packages/chrome/src/pages/AppLayout/Header/index.tsx
Labels: enhancement

#49 feat: add history list
  package-lock.json
  packages/chrome/package.json
  packages/chrome/src/pages/AppLayout/index.tsx
  packages/chrome/src/pages/TransactionFlow/TransactionItem.tsx
  packages/chrome/src/pages/TransactionFlow/assets/airdrop_detail.svg
  packages/chrome/src/pages/TransactionFlow/assets/airdrop_fail.svg
  packages/chrome/src/pages/TransactionFlow/assets/back.svg
  packages/chrome/src/pages/TransactionFlow/assets/pending.svg
  packages/chrome/src/pages/TransactionFlow/assets/receive_detail.svg
  packages/chrome/src/pages/TransactionFlow/assets/receive_fail.svg
  packages/chrome/src/pages/TransactionFlow/assets/sent_detail.svg
  packages/chrome/src/pages/TransactionFlow/assets/sent_fail.svg
  packages/chrome/src/pages/TransactionFlow/index.tsx
  packages/chrome/src/pages/TransactionFlow/transactionDetail.scss
  packages/chrome/src/pages/TransactionFlow/transactionDetail.tsx
  packages/chrome/src/pages/TransactionFlow/transactionItem.scss
Labels: enhancement

#50 fix: fix address
  packages/chrome/src/pages/TransactionFlow/index.tsx
Labels: bug

#51 feat: add swr
  packages/chrome/src/hooks/useTransactionList.ts
  packages/chrome/src/pages/TransactionFlow/index.tsx
Labels: enhancement

#52 feat: add common setting back
  packages/chrome/src/pages/SettingsPage/assets/cancel.svg
  packages/chrome/src/pages/SettingsPage/nav.tsx
  packages/chrome/src/pages/SettingsPage/network.tsx
  packages/chrome/src/pages/SettingsPage/security.tsx
  packages/chrome/src/pages/SettingsPage/wallet.tsx
Labels: enhancement

#53 feat: add common setting back
  packages/chrome/src/pages/SettingsPage/common.scss
  packages/chrome/src/pages/SettingsPage/nav.tsx
  packages/chrome/src/pages/TransactionFlow/index.tsx
Labels: enhancement

#54 fix: fix order
  packages/chrome/src/pages/TransactionFlow/index.tsx
Labels: bug

#55 feat: support explorer
  packages/chrome/src/pages/TransactionFlow/index.tsx
  packages/chrome/src/pages/TransactionFlow/transactionDetail.tsx
  packages/core/src/provider.ts
  packages/core/src/storage/types.ts
Labels: enhancement

#56 fix(ext): fix some bugs
  packages/chrome/src/pages/OnBoarding/CreateNewWallet/index.tsx
  packages/chrome/src/pages/OnBoarding/ImportWallet/index.tsx
  packages/chrome/src/pages/TransactionFlow/index.tsx
Labels: bug

#63 feat: add error handling
  packages/chrome/src/App.tsx
  packages/chrome/src/components/ErrorBoundary/index.tsx
  packages/chrome/src/pages/ErrorPage/index.module.scss
  packages/chrome/src/pages/ErrorPage/index.tsx
  packages/chrome/src/pages/SendPage/index.tsx
Labels: enhancement

#74 feat(db): db migration scripts
  packages/chrome/src/scripts/background/api-proxy.ts
  packages/core/src/api/auth.ts
  packages/core/src/storage/indexeddb.ts
  packages/core/src/storage/migrations/indexeddb.ts
  packages/core/src/storage/types.ts
  packages/core/src/utils/index.ts
Labels: enhancement

#76 feat: support dapp connection
  packages/chrome/public/dapp-api.js
  packages/chrome/src/assets/icons/link.svg
  packages/chrome/src/assets/icons/perm-no.svg
  packages/chrome/src/assets/icons/perm-yes.svg
  packages/chrome/src/hooks/useLocationSearch.ts
  packages/chrome/src/hooks/useWallet.ts
  packages/chrome/src/main.tsx
  packages/chrome/src/manifest.ts
  packages/chrome/src/pages/AppLayout/index.tsx
  packages/chrome/src/pages/dapp/ConnectPage/index.module.scss
  packages/chrome/src/pages/dapp/ConnectPage/index.tsx
  packages/chrome/src/routes/index.tsx
  packages/chrome/src/scripts/background/api-proxy.ts
  packages/chrome/src/scripts/background/bg-api/dapp.ts
  packages/chrome/src/scripts/background/permission.ts
  packages/chrome/src/scripts/background/popup-window.ts
  packages/chrome/src/scripts/content/dapp-api.ts
  packages/chrome/src/scripts/content/index.ts
  packages/chrome/src/scripts/shared/msg-passing/window-msg-stream.ts
  packages/chrome/src/store/enum.ts
Labels: enhancement

#77 fix(ext): cancel logic in connection page
  packages/chrome/src/pages/dapp/ConnectPage/index.tsx
Labels: bug

#78 feat(ext): support dapp executeMoveCall
  packages/chrome/public/dapp-api.js
  packages/chrome/src/components/Avatar/index.module.scss
  packages/chrome/src/components/Avatar/index.tsx
  packages/chrome/src/components/HyperLink/index.module.scss
  packages/chrome/src/components/HyperLink/index.tsx
  packages/chrome/src/pages/SettingsPage/wallet.tsx
  packages/chrome/src/pages/dapp/ConnectPage/index.module.scss
  packages/chrome/src/pages/dapp/ConnectPage/index.tsx
  packages/chrome/src/pages/dapp/TxApprovePage/index.module.scss
  packages/chrome/src/pages/dapp/TxApprovePage/index.tsx
  packages/chrome/src/pages/dapp/WalletSelector/index.module.scss
  packages/chrome/src/pages/dapp/WalletSelector/index.tsx
  packages/chrome/src/routes/index.tsx
  packages/chrome/src/scripts/background/bg-api/dapp.ts
  packages/chrome/src/scripts/background/permission.ts
  packages/chrome/src/scripts/background/transaction.ts
  packages/chrome/src/scripts/content/dapp-api.ts
  packages/chrome/src/store/enum.ts
  packages/core/src/api/txn.ts
  packages/core/src/provider.ts
Labels: enhancement

#80 fix: fix tx list
  packages/chrome/src/pages/TransactionFlow/index.tsx
Labels: bug

#81 refactor(ext): dapp interaction
  packages/chrome/public/dapp-api.js
  packages/chrome/src/components/HyperLink/index.module.scss
  packages/chrome/src/pages/AppLayout/Header/index.tsx
  packages/chrome/src/pages/dapp/ConnectPage/index.tsx
  packages/chrome/src/pages/dapp/TxApprovePage/index.tsx
  packages/chrome/src/pages/dapp/WalletSelector/index.tsx
  packages/chrome/src/scripts/background/api-proxy.ts
  packages/chrome/src/scripts/background/bg-api/dapp.ts
  packages/chrome/src/scripts/background/errors.ts
  packages/chrome/src/scripts/background/index.ts
  packages/chrome/src/scripts/content/dapp-api.ts
  packages/chrome/src/scripts/content/index.ts
Labels: refactor

#82 chore: mute console logs
  packages/chrome/public/dapp-api.js
  packages/chrome/src/pages/dapp/TxApprovePage/index.tsx
  packages/chrome/src/scripts/content/dapp-api.ts
  packages/chrome/src/scripts/content/index.ts
  packages/chrome/src/scripts/shared/msg-passing/window-msg-stream.ts
Labels: chore

#83 feat(ext): show normalized function info
  package-lock.json
  packages/chrome/package.json
  packages/chrome/src/App.tsx
  packages/chrome/src/pages/dapp/TxApprovePage/index.module.scss
  packages/chrome/src/pages/dapp/TxApprovePage/index.tsx
  packages/chrome/src/scripts/background/bg-api/dapp.ts
  packages/chrome/src/scripts/background/transaction.ts
  packages/chrome/src/utils/sui.ts
  packages/core/src/api/txn.ts
  packages/core/src/provider.ts
Labels: enhancement

#84 fix: content script disconnect logic
  packages/chrome/src/pages/dapp/TxApprovePage/index.tsx
  packages/chrome/src/scripts/content/index.ts
Labels: bug

#87 fix(ext): modify wallet name
  packages/chrome/src/hooks/useWallet.ts
  packages/chrome/src/pages/SettingsPage/wallet.tsx
  packages/chrome/src/pages/dapp/ConnectPage/index.tsx
  packages/chrome/src/pages/dapp/WalletSelector/index.tsx
Labels: bug

#88 feat(ext): format error
  packages/chrome/src/scripts/shared/__tests__/ui-api-client.test.ts
  packages/chrome/src/scripts/shared/ui-api-client.ts
Labels: enhancement
